#########################################################################
#									#
# File ID: ./.github/workflows/build-test.yml				#
# Author: Copyright (C) 2021  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# Configuration file for GitHub Actions build tests. Perform a standard #
# build, check and distcheck.                   			#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 27/02/2021	MG	1.0.1	Initial release.                        #
# 22/11/2021    MG      1.0.2   Get tags as needed for git-enhanced     #
#                               AC_INIT.                                #
#                               Tighten SPDX tag.                       #
#									#
#########################################################################


name: Build Test

on:
  push:

  # Allows manual invocation from the Actions tab.
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-18.04

    steps:
      # Check-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get all incl tags, needed for git-enhanced AC_INIT

      - name: Add the extra PPA
        run: sudo add-apt-repository ppa:m-grant-prg/utils -y
      - name: Update the package list
        run: sudo apt-get update
      - name: Add the extra PPA packages
        run: sudo apt-get install -y txt2man txt2manwrap

      - name: Autoreconf
        run: autoreconf -if .
      - name: Configure
        run: ./configure --enable-silent-rules=yes
      - name: Make
        run: make --quiet

      - name: Check
        run: make --quiet check

      - name: Distcheck
        run: make --quiet distcheck

